### ISSUE TITLE
5.3.3 build error

### ISSUE THREAD

**Issue by rks118** [opennextjs/opennextjs-netlify#2499]
It's correct when the project uses 5.3.2: https://app.netlify.com/sites/preview-codexfield/deploys/666448005925280008de9a6b

But, occur when 5.3.3:

Netlify log: https://app.netlify.com/sites/preview-codexfield/deploys/6671a19df33c840008195a6c

**Comment by pieh** [comment]
The failure happens during build command (~`next build`). At this point Next Runtime didn't do a lot of work yet and this part of work didn't change from `5.3.2` to `5.3.3` so the failure at this step caused by Next Runtime bump seems quite confusing. Would you be able to downgrade runtime to `5.3.2` without making any other changes to verify that this failure could be cause by runtime version?

**Comment by orinokai** [comment]
hi @rks118 we'd like to help you get this fixed! because it doesn't seem to be an issue with the Next Runtime itself I think you'll get faster and more detailed help in the [support forums](https://answers.netlify.com/)
